-- ============================================================================
--  POWERKING NEPAL — COMPLETE SCHEMA, IN ONE PASTE
-- ============================================================================
--  Supabase dashboard → SQL Editor → paste this whole file → Run.
--
--  This is every file in supabase/migrations/ concatenated, in order. Each one
--  is idempotent — it creates nothing that already exists and touches no data —
--  so running this on a project that is fully migrated, partly migrated, or
--  empty all end in the same place. Running it twice is safe.
--
--  Afterwards run supabase/apply/02-catalogue.sql, which loads the 87 real
--  products. Then create your first user (README §14) and you are done.
--
--  Generated by scripts/build-apply-sql.js — do not edit, regenerate.
-- ============================================================================


-- ===========================================================================
--  20260908090000_inventory_core.sql
-- ===========================================================================

-- ============================================================================
--  POWERKING NEPAL — INVENTORY CORE SCHEMA
-- ============================================================================
--  Creates every table the inventory system uses. Safe to run on a fresh
--  Supabase project; it creates nothing that already exists and touches no
--  data. RLS is enabled here but the policies live in the next migration, so
--  between the two nobody can read anything — which is the safe order.
--
--  Money is numeric(12,2), never float. A rupee figure that drifts by a
--  fraction because of binary floating point is a figure nobody quoted.
-- ============================================================================

create extension if not exists "pgcrypto";   -- gen_random_uuid()
create extension if not exists "pg_trgm";    -- fast ILIKE search on name/sku

-- --------------------------------------------------------------- enums ----

do $$ begin
  create type public.user_role as enum ('admin', 'manager', 'staff');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.movement_type as enum (
    'STOCK_IN', 'STOCK_OUT',
    'ADJUSTMENT_IN', 'ADJUSTMENT_OUT',
    'RETURN_IN', 'RETURN_OUT'
  );
exception when duplicate_object then null; end $$;

-- Shared updated_at trigger. Every table that carries updated_at uses it, so
-- the column is never something the application has to remember to set.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ------------------------------------------------------------ profiles ----
-- One row per Supabase Auth user. Role lives here, not in JWT claims, so an
-- admin can change somebody's role and have it take effect on their next
-- request rather than on their next login.

create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  email       text,
  role        public.user_role not null default 'staff',
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- A new auth user gets a profile automatically, inactive-by-default reasoning
-- does not apply: an admin had to create the auth user in the first place.
-- The very first user of an empty system becomes the admin, because otherwise
-- there is nobody able to promote anyone.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  first_user boolean;
begin
  select count(*) = 0 into first_user from public.profiles;
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    case
      when first_user then 'admin'::public.user_role
      when (new.raw_user_meta_data ->> 'role') in ('admin', 'manager', 'staff')
        then (new.raw_user_meta_data ->> 'role')::public.user_role
      else 'staff'::public.user_role
    end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- -------------------------------------------------------------- brands ----

create table if not exists public.brands (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  slug        text not null unique,
  logo        text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists brands_touch on public.brands;
create trigger brands_touch before update on public.brands
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------- categories ----

create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  slug        text not null unique,
  description text not null default '',
  image       text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

drop trigger if exists categories_touch on public.categories;
create trigger categories_touch before update on public.categories
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------- suppliers ----

create table if not exists public.suppliers (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  contact_person text,
  phone          text,
  email          text,
  address        text,
  notes          text,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create unique index if not exists suppliers_name_key on public.suppliers (lower(name));

drop trigger if exists suppliers_touch on public.suppliers;
create trigger suppliers_touch before update on public.suppliers
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------- inventory_locations ----
-- One warehouse today. The table exists so a second one is a row, not a
-- migration, and so every movement already records where it happened.

create table if not exists public.inventory_locations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  address     text,
  description text,
  is_default  boolean not null default false,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Exactly one location may be the default, enforced by the database rather
-- than by whichever screen happens to be setting it.
create unique index if not exists inventory_locations_one_default
  on public.inventory_locations (is_default) where is_default;

insert into public.inventory_locations (name, description, is_default)
values ('Main Warehouse', 'Default storage location.', true)
on conflict (name) do nothing;

-- ------------------------------------------------------------ products ----

create table if not exists public.products (
  id                     uuid primary key default gen_random_uuid(),
  sku                    text not null,
  name                   text not null,
  slug                   text not null,
  description            text not null default '',
  brand_id               uuid references public.brands (id) on delete set null,
  category_id            uuid not null references public.categories (id) on delete restrict,
  product_image          text,
  gallery_images         text[] not null default '{}',
  units_per_carton       integer not null default 1  check (units_per_carton > 0),
  cost_price             numeric(12,2) not null default 0 check (cost_price      >= 0),
  wholesale_price        numeric(12,2) not null default 0 check (wholesale_price >= 0),
  retail_price           numeric(12,2) not null default 0 check (retail_price    >= 0),
  -- Not in the original field list, and here because this shop genuinely
  -- quotes two trade prices: one per loose piece and a keener one per carton.
  -- The carton rate is not units_per_carton x the piece rate — that is the
  -- discount — so it cannot be derived and has to be stored.
  carton_price           numeric(12,2) check (carton_price >= 0),
  minimum_order_quantity integer not null default 1  check (minimum_order_quantity > 0),
  low_stock_threshold    integer not null default 10 check (low_stock_threshold >= 0),
  is_active              boolean not null default true,
  is_featured            boolean not null default false,
  tags                   text[] not null default '{}',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint products_sku_not_blank  check (length(btrim(sku))  > 0),
  constraint products_name_not_blank check (length(btrim(name)) > 0),
  constraint products_slug_shape     check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

-- SKU is unique case-insensitively: "pk-jbl-001" and "PK-JBL-001" are the
-- same code written by two different people, not two products.
create unique index if not exists products_sku_key  on public.products (lower(sku));
create unique index if not exists products_slug_key on public.products (slug);

create index if not exists products_category_idx on public.products (category_id);
create index if not exists products_brand_idx    on public.products (brand_id);
create index if not exists products_active_idx   on public.products (is_active);
create index if not exists products_created_idx  on public.products (created_at desc);
-- Trigram indexes make ILIKE '%term%' an index scan instead of a table scan,
-- which is what keeps search usable at the 10,000-product target.
create index if not exists products_name_trgm on public.products using gin (name gin_trgm_ops);
create index if not exists products_sku_trgm  on public.products using gin (sku  gin_trgm_ops);

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------- inventory ----
-- Current state, one row per product per location. Derivable by replaying
-- stock_movements, kept materialised because every screen reads it and no
-- screen should be summing a hundred thousand rows to draw a badge.

create table if not exists public.inventory (
  id                 uuid primary key default gen_random_uuid(),
  product_id         uuid not null references public.products (id) on delete cascade,
  location_id        uuid not null references public.inventory_locations (id) on delete restrict,
  quantity           integer not null default 0 check (quantity >= 0),
  reserved_quantity  integer not null default 0 check (reserved_quantity >= 0),
  warehouse_location text,
  updated_at         timestamptz not null default now(),
  unique (product_id, location_id),
  -- Stock cannot go negative and cannot be reserved twice. Business rule 2
  -- of the brief, expressed where no application bug can get around it.
  constraint inventory_reserved_within_stock check (reserved_quantity <= quantity)
);

create index if not exists inventory_product_idx  on public.inventory (product_id);
create index if not exists inventory_location_idx on public.inventory (location_id);

drop trigger if exists inventory_touch on public.inventory;
create trigger inventory_touch before update on public.inventory
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------- stock_movements ----
-- The ledger. Append-only in practice: there is no UPDATE or DELETE policy on
-- this table for anybody, including admins, so history cannot be quietly
-- rewritten. product_id is ON DELETE RESTRICT, which is what makes "a product
-- with transactions cannot be deleted" a database fact rather than a hope.

create table if not exists public.stock_movements (
  id               uuid primary key default gen_random_uuid(),
  product_id       uuid not null references public.products (id) on delete restrict,
  location_id      uuid references public.inventory_locations (id) on delete set null,
  movement_type    public.movement_type not null,
  quantity         integer not null check (quantity > 0),
  quantity_after   integer,
  reference_number text,
  supplier_id      uuid references public.suppliers (id) on delete set null,
  customer_name    text,
  reason           text,
  notes            text,
  unit_cost        numeric(12,2) check (unit_cost >= 0),
  created_by       uuid references public.profiles (id) on delete set null,
  created_by_name  text,
  created_at       timestamptz not null default now()
);

create index if not exists stock_movements_product_idx  on public.stock_movements (product_id);
create index if not exists stock_movements_created_idx  on public.stock_movements (created_at desc);
create index if not exists stock_movements_type_idx     on public.stock_movements (movement_type);
create index if not exists stock_movements_supplier_idx on public.stock_movements (supplier_id);
create index if not exists stock_movements_user_idx     on public.stock_movements (created_by);
-- The product detail page asks for one product's history newest-first; the
-- composite index answers that without a sort.
create index if not exists stock_movements_product_date_idx
  on public.stock_movements (product_id, created_at desc);

-- ------------------------------------------------------------ settings ----
-- Small key/value store for things the shop can change without a deploy,
-- such as whether the public catalogue shows stock badges at all.

create table if not exists public.app_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now(),
  updated_by  uuid references public.profiles (id) on delete set null
);

insert into public.app_settings (key, value) values
  ('public_stock_display', '{"mode":"badge"}'::jsonb)
on conflict (key) do nothing;

-- ----------------------------------------------------------------- RLS ----
-- Enabled on everything now. With no policies yet, this denies all access,
-- including to anon — the next migration opens exactly the doors intended.

alter table public.profiles            enable row level security;
alter table public.brands              enable row level security;
alter table public.categories          enable row level security;
alter table public.suppliers           enable row level security;
alter table public.inventory_locations enable row level security;
alter table public.products            enable row level security;
alter table public.inventory           enable row level security;
alter table public.stock_movements     enable row level security;
alter table public.app_settings        enable row level security;

-- ===========================================================================
--  20260908090100_rls_policies.sql
-- ===========================================================================

-- ============================================================================
--  POWERKING NEPAL — ROLES AND ROW LEVEL SECURITY
-- ============================================================================
--  Every permission in the brief is enforced here, in Postgres, against the
--  caller's JWT. The admin console checks the same rules in JavaScript only to
--  decide which buttons to draw; if that check were removed entirely, or the
--  page were replaced with a hand-written fetch, nothing below would change.
--
--  ── WHY THE HELPERS ARE SECURITY DEFINER ─────────────────────────────────
--  A policy on `profiles` that reads `profiles` to find the caller's role
--  recurses. These functions run as their owner and so read the table without
--  re-entering its policies. They are the only place that happens, they take
--  no arguments, and they return one row about the caller and nothing else.
-- ============================================================================

-- --------------------------------------------------------- role helpers ----

-- The caller's role, or null for anonymous callers and for a user whose
-- profile has been deactivated. Deactivating a profile therefore revokes
-- everything immediately, without touching their auth account.
create or replace function public.auth_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid() and p.is_active
$$;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.auth_role() is not null, false)
$$;

-- coalesce, and not a bare comparison: auth_role() is null for a signed-out
-- or deactivated caller, and `null = 'admin'` is null, not false. A guard
-- written `if not is_admin() then raise` would then not raise at all, because
-- `not null` is null and the branch is skipped. These must return a real
-- boolean or every caller has to remember that they might not.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.auth_role() = 'admin', false)
$$;

-- "Manager or above". Named for the permission it grants rather than for the
-- role, because every caller wants the question and not the enumeration.
create or replace function public.can_manage()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.auth_role() in ('admin', 'manager'), false)
$$;

comment on function public.auth_role is
  'Role of the calling user, or null if anonymous or deactivated. SECURITY DEFINER to avoid recursive policy evaluation on profiles.';

-- ------------------------------------------------------------ profiles ----
-- Everyone signed in can see the team: a stock movement is worthless as an
-- audit record if the name beside it cannot be resolved. Only an admin can
-- create, change roles, or deactivate. A user may edit their own name.

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select to authenticated
  using (public.is_staff() or id = auth.uid());

drop policy if exists profiles_insert_admin on public.profiles;
create policy profiles_insert_admin on public.profiles
  for insert to authenticated
  with check (public.is_admin());

drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles
  for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Own name only. The USING clause picks the row; the WITH CHECK clause makes
-- sure the row still belongs to the caller afterwards. Role and is_active are
-- guarded by the trigger below, because a policy cannot see old vs new.
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- Stops a non-admin from promoting themselves through the self-update policy.
create or replace function public.guard_profile_privileges()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_admin() then
    -- An admin must not be able to lock the system by removing the last one.
    if (old.role = 'admin' and (new.role <> 'admin' or new.is_active = false))
       and (select count(*) from public.profiles
            where role = 'admin' and is_active and id <> old.id) = 0 then
      raise exception 'PK_LAST_ADMIN: the last active admin cannot be demoted or deactivated';
    end if;
    return new;
  end if;
  if new.role is distinct from old.role or new.is_active is distinct from old.is_active then
    raise exception 'PK_FORBIDDEN: only an admin may change a role or activation';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_privileges();

drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin on public.profiles
  for delete to authenticated using (public.is_admin());

-- --------------------------------------- reference data: read for staff ----
-- brands, categories, suppliers, locations: any signed-in user reads them,
-- because every form needs the dropdown. Writing is manager-and-above, and
-- deleting is admin only.
--
-- Suppliers are commercially sensitive (business rule 7) but that means "not
-- public", not "not visible to the team" — a stock-in screen has to name the
-- supplier the goods came from. They are unreachable to anon; see the public
-- catalogue migration, which grants anon nothing on any base table.

do $$
declare t text;
begin
  foreach t in array array['brands', 'categories', 'suppliers', 'inventory_locations']
  loop
    execute format('drop policy if exists %I_select on public.%I', t, t);
    execute format(
      'create policy %I_select on public.%I for select to authenticated using (public.is_staff())', t, t);

    execute format('drop policy if exists %I_insert on public.%I', t, t);
    execute format(
      'create policy %I_insert on public.%I for insert to authenticated with check (public.can_manage())', t, t);

    execute format('drop policy if exists %I_update on public.%I', t, t);
    execute format(
      'create policy %I_update on public.%I for update to authenticated using (public.can_manage()) with check (public.can_manage())', t, t);

    execute format('drop policy if exists %I_delete on public.%I', t, t);
    execute format(
      'create policy %I_delete on public.%I for delete to authenticated using (public.is_admin())', t, t);
  end loop;
end $$;

-- ------------------------------------------------------------ products ----
-- Staff read everything, including inactive products, because they still have
-- to find one to reactivate it. Manager and above write. Only an admin may
-- DELETE, and even then only a product with no history: stock_movements holds
-- ON DELETE RESTRICT, so the delete fails at the foreign key rather than
-- taking the ledger with it.

drop policy if exists products_select on public.products;
create policy products_select on public.products
  for select to authenticated using (public.is_staff());

drop policy if exists products_insert on public.products;
create policy products_insert on public.products
  for insert to authenticated with check (public.can_manage());

drop policy if exists products_update on public.products;
create policy products_update on public.products
  for update to authenticated
  using (public.can_manage()) with check (public.can_manage());

drop policy if exists products_delete on public.products;
create policy products_delete on public.products
  for delete to authenticated using (public.is_admin());

-- ----------------------------------------------------------- inventory ----
-- Read for all staff. NOT writable by anybody through the table, at any role:
-- there is deliberately no INSERT, UPDATE or DELETE policy here. The only way
-- stock changes is record_stock_movement(), which writes the ledger in the
-- same transaction. That is business rule 3 made structural — you cannot
-- forget to record a movement, because you cannot reach the quantity column.

drop policy if exists inventory_select on public.inventory;
create policy inventory_select on public.inventory
  for select to authenticated using (public.is_staff());

-- Bin/shelf text is a label, not a quantity, so a manager may edit it
-- directly. The column list is not restrictable in a policy, so the trigger
-- below rejects any attempt to move a number through this door.
drop policy if exists inventory_update_label on public.inventory;
create policy inventory_update_label on public.inventory
  for update to authenticated
  using (public.can_manage()) with check (public.can_manage());

create or replace function public.guard_inventory_quantities()
returns trigger language plpgsql set search_path = public as $$
begin
  -- record_stock_movement() sets this flag for the duration of its
  -- transaction; anything else changing a quantity is a bug or an attack.
  if current_setting('powerking.stock_rpc', true) = 'on' then
    return new;
  end if;
  if new.quantity is distinct from old.quantity
     or new.reserved_quantity is distinct from old.reserved_quantity then
    raise exception
      'PK_NO_SILENT_STOCK: stock is changed with record_stock_movement(), so that a movement is always recorded';
  end if;
  return new;
end;
$$;

drop trigger if exists inventory_guard on public.inventory;
create trigger inventory_guard before update on public.inventory
  for each row execute function public.guard_inventory_quantities();

-- ----------------------------------------------------- stock_movements ----
-- Read for all staff — the audit trail is the point, hiding it from the
-- people doing the work would defeat it. Insert only through the RPC (which
-- is SECURITY DEFINER and so is not subject to this policy); there is no
-- direct INSERT policy, and no UPDATE or DELETE policy for anyone at all.
-- Business rule 4: history cannot be casually deleted, by anybody, ever.

drop policy if exists stock_movements_select on public.stock_movements;
create policy stock_movements_select on public.stock_movements
  for select to authenticated using (public.is_staff());

-- -------------------------------------------------------- app_settings ----

drop policy if exists app_settings_select on public.app_settings;
create policy app_settings_select on public.app_settings
  for select to authenticated using (public.is_staff());

drop policy if exists app_settings_write on public.app_settings;
create policy app_settings_write on public.app_settings
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ===========================================================================
--  20260908090200_stock_functions.sql
-- ===========================================================================

-- ============================================================================
--  POWERKING NEPAL — STOCK MUTATION FUNCTIONS
-- ============================================================================
--  The only way stock changes. Each function does the whole job in one
--  transaction: lock the stock row, check the result would not be negative,
--  write the new quantity, write the ledger entry. If any part fails the whole
--  thing rolls back, so `inventory` and `stock_movements` cannot disagree.
--
--  ── WHY THE ROW LOCK MATTERS ─────────────────────────────────────────────
--  Two people on two phones selling the last carton at the same moment both
--  read "1 in stock", both subtract 1, and the shop is now at -1 with two
--  movements recorded. SELECT ... FOR UPDATE makes the second one wait for
--  the first to commit, so it reads 0 and is rejected. Without it the check
--  is decoration.
--
--  ── ERROR CODES ──────────────────────────────────────────────────────────
--  Messages are prefixed PK_ and the admin console maps them to plain
--  English. Anything without a prefix is unexpected and is shown as a generic
--  failure, so a raw Postgres error never reaches a member of staff.
-- ============================================================================

-- Does this movement type add stock or remove it?
create or replace function public.movement_sign(t public.movement_type)
returns integer language sql immutable as $$
  select case when t in ('STOCK_IN', 'ADJUSTMENT_IN', 'RETURN_IN') then 1 else -1 end
$$;

-- The location a movement lands in when the caller did not name one.
create or replace function public.default_location_id()
returns uuid language sql stable as $$
  select id from public.inventory_locations
  where is_default and is_active
  order by created_at limit 1
$$;

-- ------------------------------------------------ record_stock_movement ----

create or replace function public.record_stock_movement(
  p_product_id       uuid,
  p_movement_type    public.movement_type,
  p_quantity         integer,
  p_location_id      uuid          default null,
  p_reference_number text          default null,
  p_supplier_id      uuid          default null,
  p_customer_name    text          default null,
  p_unit_cost        numeric       default null,
  p_reason           text          default null,
  p_notes            text          default null,
  p_occurred_at      timestamptz   default null
)
returns public.stock_movements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role      public.user_role := public.auth_role();
  v_uid       uuid := auth.uid();
  v_name      text;
  v_location  uuid;
  v_sign      integer := public.movement_sign(p_movement_type);
  v_before    integer;
  v_after     integer;
  v_reserved  integer;
  v_inv       public.inventory%rowtype;
  v_movement  public.stock_movements%rowtype;
  v_active    boolean;
begin
  -- --- who is asking -------------------------------------------------------
  if v_role is null then
    raise exception 'PK_FORBIDDEN: your account is not authorised to change stock';
  end if;
  -- Staff may move stock in and out; only manager and above may write off
  -- a discrepancy, because an adjustment is the one movement with no
  -- counterparty to check it against.
  if p_movement_type in ('ADJUSTMENT_IN', 'ADJUSTMENT_OUT') and v_role = 'staff' then
    raise exception 'PK_FORBIDDEN: adjustments may only be made by a manager or an admin';
  end if;

  select full_name into v_name from public.profiles where id = v_uid;

  -- --- validate the request ------------------------------------------------
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'PK_BAD_QUANTITY: quantity must be a whole number greater than zero';
  end if;
  if p_unit_cost is not null and p_unit_cost < 0 then
    raise exception 'PK_BAD_AMOUNT: unit cost cannot be negative';
  end if;

  select is_active into v_active from public.products where id = p_product_id;
  if not found then
    raise exception 'PK_NO_PRODUCT: that product no longer exists';
  end if;
  -- An inactive product can still receive a return or a correction; it just
  -- cannot be sold. Blocking every movement would strand its remaining stock.
  if not v_active and p_movement_type in ('STOCK_IN', 'STOCK_OUT') then
    raise exception 'PK_INACTIVE_PRODUCT: reactivate this product before moving stock in or out';
  end if;

  v_location := coalesce(p_location_id, public.default_location_id());
  if v_location is null then
    raise exception 'PK_NO_LOCATION: no active storage location has been set up';
  end if;

  -- --- lock, compute, apply ------------------------------------------------
  -- The insert covers a product that has never held stock at this location.
  -- ON CONFLICT DO NOTHING then a locking select, rather than upsert, so the
  -- row is locked whether we created it or somebody else did.
  insert into public.inventory (product_id, location_id, quantity)
  values (p_product_id, v_location, 0)
  on conflict (product_id, location_id) do nothing;

  select * into v_inv from public.inventory
  where product_id = p_product_id and location_id = v_location
  for update;

  v_before   := v_inv.quantity;
  v_reserved := v_inv.reserved_quantity;
  v_after    := v_before + (v_sign * p_quantity);

  if v_after < 0 then
    raise exception
      'PK_INSUFFICIENT_STOCK: only % in stock, cannot remove %', v_before, p_quantity;
  end if;
  -- Stock already promised to somebody cannot also be shipped to somebody
  -- else. reserved_quantity is 0 everywhere in this version, so this is
  -- dormant until reservations are switched on — but it is the check that
  -- will matter then, and adding it later means auditing every caller again.
  if v_after < v_reserved then
    raise exception
      'PK_RESERVED_STOCK: % of the % in stock are reserved, so only % can be removed',
      v_reserved, v_before, v_before - v_reserved;
  end if;

  -- Tells the inventory guard trigger that this write came through the front
  -- door. `true` scopes it to this transaction, so it cannot leak to the
  -- next request on a pooled connection.
  perform set_config('powerking.stock_rpc', 'on', true);

  update public.inventory
  set quantity = v_after, updated_at = now()
  where id = v_inv.id;

  insert into public.stock_movements (
    product_id, location_id, movement_type, quantity, quantity_after,
    reference_number, supplier_id, customer_name, reason, notes, unit_cost,
    created_by, created_by_name, created_at
  ) values (
    p_product_id, v_location, p_movement_type, p_quantity, v_after,
    nullif(btrim(coalesce(p_reference_number, '')), ''),
    p_supplier_id,
    nullif(btrim(coalesce(p_customer_name, '')), ''),
    nullif(btrim(coalesce(p_reason, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''),
    p_unit_cost,
    v_uid, v_name, coalesce(p_occurred_at, now())
  )
  returning * into v_movement;

  perform set_config('powerking.stock_rpc', 'off', true);
  return v_movement;
end;
$$;

comment on function public.record_stock_movement is
  'The only supported way to change stock. Locks the inventory row, refuses to go negative, and writes inventory and stock_movements in one transaction.';

-- ------------------------------------------------------ create_product ----
-- A product and its inventory row are created together, with an optional
-- opening balance recorded as a real STOCK_IN so day one is in the ledger
-- too. Without this the first screen a new product reaches would show stock
-- that no movement explains.

create or replace function public.create_product(
  p_product        jsonb,
  p_opening_stock  integer default 0,
  p_location_id    uuid    default null,
  p_warehouse_note text    default null
)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product  public.products%rowtype;
  v_location uuid;
begin
  if not public.can_manage() then
    raise exception 'PK_FORBIDDEN: only a manager or an admin may add a product';
  end if;
  if p_opening_stock is null or p_opening_stock < 0 then
    raise exception 'PK_BAD_QUANTITY: opening stock cannot be negative';
  end if;

  v_location := coalesce(p_location_id, public.default_location_id());

  begin
    insert into public.products (
      sku, name, slug, description, brand_id, category_id,
      product_image, gallery_images, units_per_carton,
      cost_price, wholesale_price, retail_price, carton_price,
      minimum_order_quantity, low_stock_threshold, is_active, is_featured, tags
    )
    select
      btrim(p_product ->> 'sku'),
      btrim(p_product ->> 'name'),
      btrim(p_product ->> 'slug'),
      coalesce(p_product ->> 'description', ''),
      nullif(p_product ->> 'brand_id', '')::uuid,
      (p_product ->> 'category_id')::uuid,
      nullif(p_product ->> 'product_image', ''),
      coalesce((select array_agg(value #>> '{}') from jsonb_array_elements(
                 coalesce(p_product -> 'gallery_images', '[]'::jsonb))), '{}'),
      coalesce((p_product ->> 'units_per_carton')::integer, 1),
      coalesce((p_product ->> 'cost_price')::numeric, 0),
      coalesce((p_product ->> 'wholesale_price')::numeric, 0),
      coalesce((p_product ->> 'retail_price')::numeric, 0),
      nullif(p_product ->> 'carton_price', '')::numeric,
      coalesce((p_product ->> 'minimum_order_quantity')::integer, 1),
      coalesce((p_product ->> 'low_stock_threshold')::integer, 10),
      coalesce((p_product ->> 'is_active')::boolean, true),
      coalesce((p_product ->> 'is_featured')::boolean, false),
      coalesce((select array_agg(value #>> '{}') from jsonb_array_elements(
                 coalesce(p_product -> 'tags', '[]'::jsonb))), '{}')
    returning * into v_product;
  exception
    when unique_violation then
      -- Two different unique indexes, two different things to fix.
      if sqlerrm like '%products_sku_key%' then
        raise exception 'PK_DUPLICATE_SKU: SKU "%" is already used by another product', p_product ->> 'sku';
      end if;
      raise exception 'PK_DUPLICATE_SLUG: the web address "%" is already taken', p_product ->> 'slug';
    when foreign_key_violation then
      raise exception 'PK_BAD_REFERENCE: the chosen category or brand no longer exists';
  end;

  if v_location is not null then
    insert into public.inventory (product_id, location_id, quantity, warehouse_location)
    values (v_product.id, v_location, 0, nullif(btrim(coalesce(p_warehouse_note, '')), ''))
    on conflict (product_id, location_id) do nothing;
  end if;

  if p_opening_stock > 0 then
    perform public.record_stock_movement(
      p_product_id    => v_product.id,
      p_movement_type => 'STOCK_IN',
      p_quantity      => p_opening_stock,
      p_location_id   => v_location,
      p_reason        => 'Opening stock',
      p_unit_cost     => nullif(v_product.cost_price, 0),
      p_notes         => 'Recorded when the product was created.'
    );
  end if;

  return v_product;
end;
$$;

-- -------------------------------------------------- deactivate_product ----
-- Soft delete, and the reason a hard delete is almost never offered: a
-- product that has ever moved is part of the ledger. This reports which case
-- it is so the console can say so rather than just refusing.

create or replace function public.product_can_be_deleted(p_product_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_admin()
     and not exists (select 1 from public.stock_movements where product_id = p_product_id)
$$;

-- ---------------------------------------------------- import_products -----
-- CSV import. Everything or nothing: one bad row raises, and the whole call
-- rolls back, so a half-imported spreadsheet is not a state this system can
-- be in. `p_dry_run` runs every check and then deliberately fails, which is
-- how the preview screen validates without writing.

create or replace function public.import_products(
  p_rows    jsonb,
  p_dry_run boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row       jsonb;
  v_index     integer := 0;
  v_created   integer := 0;
  v_errors    jsonb := '[]'::jsonb;
  v_opening   integer;
  v_cat       uuid;
  v_brand     uuid;
  v_message   text;
begin
  if not public.can_manage() then
    raise exception 'PK_FORBIDDEN: only a manager or an admin may import products';
  end if;

  for v_row in select * from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb))
  loop
    v_index := v_index + 1;
    v_cat := nullif(v_row ->> 'category_id', '')::uuid;
    v_brand := nullif(v_row ->> 'brand_id', '')::uuid;
    v_opening := coalesce((v_row ->> 'opening_stock')::integer, 0);

    begin
      -- PERFORM, not SELECT ... INTO: create_product returns a composite, and
      -- assigning that to a %rowtype variable would try to put the whole row
      -- into its first column.
      perform public.create_product(
        (v_row - 'opening_stock')
          || jsonb_build_object('category_id', v_cat, 'brand_id', v_brand),
        v_opening
      );
      v_created := v_created + 1;
    exception when others then
      get stacked diagnostics v_message = message_text;
      v_errors := v_errors || jsonb_build_object(
        'row', v_index,
        'sku', v_row ->> 'sku',
        'message', v_message
      );
    end;
  end loop;

  if jsonb_array_length(v_errors) > 0 then
    raise exception 'PK_IMPORT_FAILED: %', v_errors::text;
  end if;

  if p_dry_run then
    -- Rolls the whole call back, including every row created above. The
    -- caller catches this code and reads it as "the preview passed".
    raise exception 'PK_DRY_RUN_OK: % rows would be imported', v_created;
  end if;

  return jsonb_build_object('created', v_created);
end;
$$;

-- ---------------------------------------------------- dashboard_summary ----
-- Five KPI cards in one round trip instead of five. Inventory value uses cost
-- price, never retail: it is what the stock cost the business, not what it
-- would fetch.

create or replace function public.dashboard_summary()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with stock as (
    select
      p.id,
      p.cost_price,
      p.low_stock_threshold,
      coalesce(sum(i.quantity), 0)::integer as qty,
      coalesce(sum(i.quantity - i.reserved_quantity), 0)::integer as available
    from public.products p
    left join public.inventory i on i.product_id = p.id
    where p.is_active
    group by p.id, p.cost_price, p.low_stock_threshold
  )
  select case when public.is_staff() then jsonb_build_object(
    'total_products',    (select count(*) from stock),
    'total_units',       (select coalesce(sum(qty), 0) from stock),
    'low_stock',         (select count(*) from stock where available > 0 and available <= low_stock_threshold),
    'out_of_stock',      (select count(*) from stock where available <= 0),
    'inventory_value',   (select coalesce(sum(qty * cost_price), 0) from stock),
    'inactive_products', (select count(*) from public.products where not is_active),
    'movements_today',   (select count(*) from public.stock_movements where created_at >= date_trunc('day', now()))
  ) else null end
$$;

-- ------------------------------------------------------------- grants -----
-- PostgREST needs EXECUTE to expose these as RPCs. Each one re-checks the
-- caller's role internally, so being callable is not being permitted.

revoke all on function public.record_stock_movement(uuid, public.movement_type, integer, uuid, text, uuid, text, numeric, text, text, timestamptz) from public;
revoke all on function public.create_product(jsonb, integer, uuid, text) from public;
revoke all on function public.import_products(jsonb, boolean) from public;

grant execute on function public.record_stock_movement(uuid, public.movement_type, integer, uuid, text, uuid, text, numeric, text, text, timestamptz) to authenticated;
grant execute on function public.create_product(jsonb, integer, uuid, text) to authenticated;
grant execute on function public.import_products(jsonb, boolean) to authenticated;
grant execute on function public.product_can_be_deleted(uuid) to authenticated;
grant execute on function public.dashboard_summary() to authenticated;
grant execute on function public.auth_role() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_manage() to authenticated;

-- ===========================================================================
--  20260908090300_public_catalogue.sql
-- ===========================================================================

-- ============================================================================
--  POWERKING NEPAL — PUBLIC CATALOGUE SURFACE
-- ============================================================================
--  What an anonymous visitor — and the site build, which uses the same
--  anonymous key — is allowed to see. Everything else is closed.
--
--  ── WHY VIEWS AND NOT A POLICY ON products ───────────────────────────────
--  An `anon` SELECT policy on `products` would grant the whole row. RLS
--  filters rows, not columns, so cost_price would travel to every browser
--  that asked for it. These views are a projection: the private columns are
--  not in them, so there is no request that returns one.
--
--  The views run with the privileges of their owner rather than the caller's
--  (`security_invoker = false`, which is the default and is stated here so it
--  is a decision rather than an accident). That is what lets them read the
--  base tables while `anon` holds no grant on those tables at all — checked
--  at the bottom of this file. Each view hard-codes `is_active`, so an
--  inactive product has no public representation to leak.
--
--  Business rules 6, 7 and 8: cost price, suppliers and exact quantities do
--  not appear below. Stock is a word, not a number.
-- ============================================================================

-- Belt and braces. PostgREST reaches these tables as `anon` for a signed-out
-- caller; with RLS on and no anon policy it would already return nothing, and
-- with no grant it cannot even be asked.
revoke all on public.products            from anon;
revoke all on public.inventory           from anon;
revoke all on public.stock_movements     from anon;
revoke all on public.suppliers           from anon;
revoke all on public.profiles            from anon;
revoke all on public.categories          from anon;
revoke all on public.brands              from anon;
revoke all on public.inventory_locations from anon;
revoke all on public.app_settings        from anon;

-- ------------------------------------------------------- stock wording ----
-- How much a visitor is told. Configurable because it is a commercial
-- decision, not a technical one: a shop that is happy to advertise depth can
-- switch it, one that is not can turn the badge off entirely.
--
--   'badge'  → In Stock / Low Stock / Out of Stock
--   'binary' → In Stock / Contact for Availability
--   'off'    → always Contact for Availability
--
-- Even on 'badge' the number itself never crosses the line.

create or replace function public.public_stock_label(
  p_mode      text,
  p_available integer,
  p_threshold integer
)
returns text
language sql
immutable
as $$
  select case p_mode
    when 'off' then 'contact'
    when 'binary' then case when coalesce(p_available, 0) > 0 then 'in_stock' else 'contact' end
    else case
      when coalesce(p_available, 0) <= 0 then 'out_of_stock'
      when p_available <= coalesce(p_threshold, 0) then 'low_stock'
      else 'in_stock'
    end
  end
$$;

-- The mode is a single row that every product on the page shares, so it is
-- read once per query as a scalar and passed in, rather than being looked up
-- per product. Taking the setting as an argument also keeps the function
-- pure: it touches no table, so it needs no privileges of its own and there
-- is no reason for it to be SECURITY DEFINER.
create or replace function public.public_stock_mode()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select value ->> 'mode' from public.app_settings where key = 'public_stock_display'),
    'badge')
$$;

-- ------------------------------------------------- catalogue_products -----

drop view if exists public.catalogue_products;
create view public.catalogue_products
with (security_invoker = false) as
select
  p.id,
  p.sku,
  p.name,
  p.slug,
  p.description,
  b.name  as brand,
  c.name  as category,
  c.slug  as category_slug,
  p.product_image,
  p.gallery_images,
  p.units_per_carton,
  -- Trade prices only. cost_price is not selected, so it cannot be returned.
  p.wholesale_price,
  p.retail_price,
  p.carton_price,
  p.minimum_order_quantity,
  p.is_featured,
  p.tags,
  public.public_stock_label(cfg.mode, coalesce(s.available, 0), p.low_stock_threshold)
    as stock_status,
  p.updated_at
from public.products p
cross join (select public.public_stock_mode() as mode) cfg
join public.categories c on c.id = p.category_id
left join public.brands b on b.id = p.brand_id
left join lateral (
  select sum(i.quantity - i.reserved_quantity)::integer as available
  from public.inventory i where i.product_id = p.id
) s on true
where p.is_active and c.is_active;

comment on view public.catalogue_products is
  'Public product projection. Active products only, no cost price, no supplier, no quantity — stock is a status word. Read by anonymous visitors and by the site build.';

-- ----------------------------------------------- catalogue_categories -----

drop view if exists public.catalogue_categories;
create view public.catalogue_categories
with (security_invoker = false) as
select
  c.id, c.name, c.slug, c.description, c.image,
  count(p.id)::integer as product_count
from public.categories c
left join public.products p on p.category_id = c.id and p.is_active
where c.is_active
group by c.id, c.name, c.slug, c.description, c.image;

-- --------------------------------------------------- catalogue_brands -----

drop view if exists public.catalogue_brands;
create view public.catalogue_brands
with (security_invoker = false) as
select
  b.id, b.name, b.slug, b.logo,
  count(p.id)::integer as product_count
from public.brands b
left join public.products p on p.brand_id = b.id and p.is_active
where b.is_active
group by b.id, b.name, b.slug, b.logo;

grant select on public.catalogue_products   to anon, authenticated;
grant select on public.catalogue_categories to anon, authenticated;
grant select on public.catalogue_brands     to anon, authenticated;
grant execute on function public.public_stock_label(text, integer, integer) to anon, authenticated;
grant execute on function public.public_stock_mode() to anon, authenticated;

-- ============================================================================
--  ADMIN READ SURFACE
-- ============================================================================
--  Joined views for the screens that would otherwise make four requests to
--  draw one table. These run as the caller (`security_invoker = true`), so
--  every policy from the previous migration still applies to them — a member
--  of staff reading `product_stock` is reading `products` and `inventory`
--  under their own permissions, through a convenience shape.

drop view if exists public.product_stock;
create view public.product_stock
with (security_invoker = true) as
select
  p.id,
  p.sku,
  p.name,
  p.slug,
  p.product_image,
  p.is_active,
  p.is_featured,
  p.units_per_carton,
  p.cost_price,
  p.wholesale_price,
  p.retail_price,
  p.carton_price,
  p.minimum_order_quantity,
  p.low_stock_threshold,
  p.brand_id,
  b.name as brand_name,
  p.category_id,
  c.name as category_name,
  coalesce(s.quantity, 0)  as quantity,
  coalesce(s.reserved, 0)  as reserved_quantity,
  coalesce(s.quantity, 0) - coalesce(s.reserved, 0) as available_quantity,
  s.locations,
  s.warehouse_location,
  case
    when coalesce(s.quantity, 0) - coalesce(s.reserved, 0) <= 0 then 'out_of_stock'
    when coalesce(s.quantity, 0) - coalesce(s.reserved, 0) <= p.low_stock_threshold then 'low_stock'
    else 'in_stock'
  end as stock_status,
  -- Value at cost, matching the dashboard. Kept here so a CSV export of this
  -- view is already the inventory report.
  round(coalesce(s.quantity, 0) * p.cost_price, 2) as inventory_value,
  p.created_at,
  p.updated_at
from public.products p
join public.categories c on c.id = p.category_id
left join public.brands b on b.id = p.brand_id
left join lateral (
  select
    sum(i.quantity)::integer          as quantity,
    sum(i.reserved_quantity)::integer as reserved,
    array_agg(distinct l.name)        as locations,
    min(i.warehouse_location)         as warehouse_location
  from public.inventory i
  join public.inventory_locations l on l.id = i.location_id
  where i.product_id = p.id
) s on true;

-- Supabase grants anon everything in `public` by default, and a view created
-- after that default is no exception. product_stock runs as the caller, so
-- anon would already read nothing through it — but a grant that is never
-- meant to be used is a grant to remove, not to reason about.
revoke all on public.product_stock from anon;
grant select on public.product_stock to authenticated;

-- Movements with the names already resolved, so the activity tables and the
-- movement report do not each re-invent the same four joins.
drop view if exists public.stock_movement_log;
create view public.stock_movement_log
with (security_invoker = true) as
select
  m.id,
  m.created_at,
  m.movement_type,
  m.quantity,
  m.quantity_after,
  public.movement_sign(m.movement_type) * m.quantity as signed_quantity,
  m.reference_number,
  m.customer_name,
  m.reason,
  m.notes,
  m.unit_cost,
  m.product_id,
  p.name as product_name,
  p.sku  as product_sku,
  m.supplier_id,
  sup.name as supplier_name,
  m.location_id,
  loc.name as location_name,
  m.created_by,
  coalesce(pr.full_name, m.created_by_name, 'Unknown') as created_by_name
from public.stock_movements m
join public.products p on p.id = m.product_id
left join public.suppliers sup on sup.id = m.supplier_id
left join public.inventory_locations loc on loc.id = m.location_id
left join public.profiles pr on pr.id = m.created_by;

revoke all on public.stock_movement_log from anon;
grant select on public.stock_movement_log to authenticated;

-- ===========================================================================
--  20260908090400_storage.sql
-- ===========================================================================

-- ============================================================================
--  POWERKING NEPAL — IMAGE STORAGE
-- ============================================================================
--  One public bucket for product photos, category images and brand logos.
--
--  Public *read* is deliberate: these images are printed on the catalogue,
--  which is a public website, and a signed URL that expires would break every
--  link a customer has ever been sent on WhatsApp. Public read, authorised
--  write — the same shape as the rest of the site.
--
--  Writing is manager-and-above. Staff record stock; they do not re-photograph
--  the catalogue, and an upload endpoint is the easiest thing in any system to
--  fill with junk.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,   -- 5 MB; a phone photo resized to a 600px tile is far under this
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "product images are publicly readable" on storage.objects;
create policy "product images are publicly readable" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'product-images');

drop policy if exists "managers upload product images" on storage.objects;
create policy "managers upload product images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and public.can_manage());

drop policy if exists "managers replace product images" on storage.objects;
create policy "managers replace product images" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images' and public.can_manage())
  with check (bucket_id = 'product-images' and public.can_manage());

-- Deleting an image orphans it from a product that may still be published, so
-- it is an admin action rather than a routine one.
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images' and public.is_admin());
