#!/usr/bin/env node
/**
 * Downloads the site's webfonts from Google Fonts and self-hosts them.
 *
 * Why self-host rather than link to the Google CDN:
 *   • one less DNS lookup + TLS handshake on a slow mobile connection
 *   • no third-party request, so no cookie/privacy question to answer
 *   • the fonts keep working if the CDN is blocked or slow
 *
 * Both families are variable fonts, so a single file covers every weight.
 * Latin + latin-ext subsets only — the site is in English.
 *
 * Fonts: Archivo (headings, up to 900) and Inter (body). Both are licensed
 * under the SIL Open Font License, which permits commercial use.
 *
 * Run:  node scripts/fetch-fonts.js     (only needed if changing typefaces)
 */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public/fonts');

// A modern desktop UA makes Google Fonts serve woff2 + variable axes.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  // Archivo carries a true 900. Space Grotesk stops at 700, which is not
  // heavy enough for the display sizes this brand runs at.
  { css: 'Archivo:wght@600..900', family: 'Archivo', file: 'archivo' },
  { css: 'Inter:wght@400..700', family: 'Inter', file: 'inter' },
];

// Keep only the subsets we actually need.
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

async function main() {
  await mkdir(OUT, { recursive: true });
  const faces = [];

  for (const { css, family, file } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${css}&display=swap`;
    const sheet = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

    // Each @font-face is preceded by a /* subset */ comment.
    const blocks = [...sheet.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];

    for (const [, subset, block] of blocks) {
      if (!WANTED_SUBSETS.has(subset)) continue;
      const src = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
      const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
      const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() || '400';
      if (!src) continue;

      const name = `${file}-${subset}.woff2`;
      const bytes = Buffer.from(
        await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer(),
      );
      await writeFile(path.join(OUT, name), bytes);
      process.stdout.write(`  ✓ ${name}  ${(bytes.length / 1024).toFixed(1)}KB  (${weight})\n`);

      faces.push({ family, name, weight, range, subset });
    }
  }

  // Emit the @font-face CSS the stylesheet imports.
  const css = `/* ==========================================================================
   SELF-HOSTED WEBFONTS  —  generated by scripts/fetch-fonts.js
   Do not edit by hand. Both families are SIL Open Font License.
   ========================================================================== */

${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.name}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')}
`;
  await writeFile(path.join(ROOT, 'src/assets/css/fonts.css'), css, 'utf8');
  process.stdout.write(`\n  ✓ src/assets/css/fonts.css  (${faces.length} faces)\n`);
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
